// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-GQQY8ypIu9JGDABmNe6-kIw0RIK1D0',
    appId: '1:778936692755:web:5f7dbb8e5d4a9755f04fe6',
    messagingSenderId: '778936692755',
    projectId: 'untittled4-5de77',
    authDomain: 'untittled4-5de77.firebaseapp.com',
    storageBucket: 'untittled4-5de77.appspot.com',
    measurementId: 'G-W5R2VVR2VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSoAwLc0m8gDDtyIt8WXzfPgm8Hhxcz8',
    appId: '1:778936692755:android:1bc82ae44f3f7743f04fe6',
    messagingSenderId: '778936692755',
    projectId: 'untittled4-5de77',
    storageBucket: 'untittled4-5de77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsF6aAW2SimbStmrwQQwzwG2Xdd2AcFDw',
    appId: '1:778936692755:ios:90da4eb383a25d8af04fe6',
    messagingSenderId: '778936692755',
    projectId: 'untittled4-5de77',
    storageBucket: 'untittled4-5de77.appspot.com',
    androidClientId: '778936692755-jott5kkhdcc8mbir2fh8730iqpe88sir.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsF6aAW2SimbStmrwQQwzwG2Xdd2AcFDw',
    appId: '1:778936692755:ios:90da4eb383a25d8af04fe6',
    messagingSenderId: '778936692755',
    projectId: 'untittled4-5de77',
    storageBucket: 'untittled4-5de77.appspot.com',
    androidClientId: '778936692755-jott5kkhdcc8mbir2fh8730iqpe88sir.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm-GQQY8ypIu9JGDABmNe6-kIw0RIK1D0',
    appId: '1:778936692755:web:0889e616b1184ef9f04fe6',
    messagingSenderId: '778936692755',
    projectId: 'untittled4-5de77',
    authDomain: 'untittled4-5de77.firebaseapp.com',
    storageBucket: 'untittled4-5de77.appspot.com',
    measurementId: 'G-GDBCS21MHS',
  );
}
