// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPt5Wfn9KWnHjeiua3N8ADtVbKolrOrw',
    appId: '1:120051000244:web:ee34b9a245c4dd277dc8e1',
    messagingSenderId: '120051000244',
    projectId: 'ecommerce-6cd39',
    authDomain: 'ecommerce-6cd39.firebaseapp.com',
    storageBucket: 'ecommerce-6cd39.firebasestorage.app',
    measurementId: 'G-4HT7F9M6DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkw9ao6VtekwIgJkC2DNIzTjXoycKTQpg',
    appId: '1:120051000244:android:22a7ec5eb1776a1d7dc8e1',
    messagingSenderId: '120051000244',
    projectId: 'ecommerce-6cd39',
    storageBucket: 'ecommerce-6cd39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIkZzBGEflt7ibt-u4hChFO1I0P9QrFU',
    appId: '1:120051000244:ios:6368fe684f277be87dc8e1',
    messagingSenderId: '120051000244',
    projectId: 'ecommerce-6cd39',
    storageBucket: 'ecommerce-6cd39.firebasestorage.app',
    androidClientId:
        '120051000244-tkbaucvhcedg6iprns791hk00m6b73qd.apps.googleusercontent.com',
    iosClientId:
        '120051000244-682lmlnsun0tqj7n8ao8ags91m6d3nnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWIkZzBGEflt7ibt-u4hChFO1I0P9QrFU',
    appId: '1:120051000244:ios:6368fe684f277be87dc8e1',
    messagingSenderId: '120051000244',
    projectId: 'ecommerce-6cd39',
    storageBucket: 'ecommerce-6cd39.firebasestorage.app',
    androidClientId:
        '120051000244-tkbaucvhcedg6iprns791hk00m6b73qd.apps.googleusercontent.com',
    iosClientId:
        '120051000244-682lmlnsun0tqj7n8ao8ags91m6d3nnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQPt5Wfn9KWnHjeiua3N8ADtVbKolrOrw',
    appId: '1:120051000244:web:b6b5431733d274867dc8e1',
    messagingSenderId: '120051000244',
    projectId: 'ecommerce-6cd39',
    authDomain: 'ecommerce-6cd39.firebaseapp.com',
    storageBucket: 'ecommerce-6cd39.firebasestorage.app',
    measurementId: 'G-8SQN7TL5GR',
  );
}
